parameters:
  notifying_database_url: 'sqlite:///%kernel.project_dir%/var/notifying_dev.sqlite'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Notifying\:
    resource: '../src/'
    exclude:
      - '../src/Entity/'
      - '../src/Kernel.php'
