services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Notifying\Controller\:
    resource: '../../src/Controller/'
    tags: ['controller.service_arguments']

  App\Notifying\Repository\:
    resource: '../../src/Repository/'

  App\Notifying\Handler\:
    resource: '../../src/Handler/'

  App\Notifying\Service\:
    resource: '../../src/Service/'
